fetch detail stats for timeRange
saucelabs/tracelib pull request #16
Opened 2019-09-17 15:46 UTC by farhan-sauce

DetailStats data was missing, which can be useful to draw following chart.

![Screen Shot 2019-09-17 at 7 31 02 PM](https://user-images.githubusercontent.com/39295560/65056455-7f8c5f00-d98e-11e9-80e2-4f7a7700d6fc.png)

2019-09-17 20:42 UTC, christian-bromann requested changes

2019-09-17 20:42 UTC, christian-bromann commented on tests/index.test.ts
> +        expect(Object.keys(result)).toMatchSnapshot()
Can we also test the values instead just keys?

2019-09-17 20:42 UTC, christian-bromann commented on tests/index.test.ts
> +        expect(Object.keys(result)).toMatchSnapshot()
same

2019-09-17 20:42 UTC, christian-bromann commented on tests/index.test.ts
> +        expect(Object.keys(result)).toMatchSnapshot()
same

2019-09-17 23:42 UTC, christian-bromann requested changes

2019-09-17 23:42 UTC, christian-bromann commented on src/utils.ts
> +        super()
the constructor function is not needed if you just call `super()` in it.

2019-09-18 06:28 UTC, farhan-sauce commented on tests/index.test.ts
> +        expect(Object.keys(result)).toMatchSnapshot()
`getDetailStats` returns big object ,it takes 234k lines in snapshot file, is it okay?

2019-09-18 06:41 UTC, christian-bromann commented on tests/index.test.ts
> +        expect(Object.keys(result)).toMatchSnapshot()
no, let's keep it this way then

2019-09-18 06:41 UTC, christian-bromann approved these changes

2019-09-18 06:41 UTC, merged