Fetch summary from traceLog
saucelabs/tracelib pull request #7
Opened 2019-08-07 10:50 UTC by farhan-sauce

2019-08-12 10:03 UTC, christian-bromann requested changes
some comments but super stoked that we get this data

2019-08-12 10:03 UTC, christian-bromann commented on src/timelineModel/index.ts
> +                if ('startTime' in eventData)
Can enforce the brackets? I intentionally added them so the code becomes more clear.

2019-08-12 10:03 UTC, christian-bromann commented on src/timelineModel/index.ts
> +                if ('startTime' in eventData)
maybe worth adding an eslint rule to it

2019-08-12 10:03 UTC, christian-bromann commented on src/timelineModel/timelineModelFilter/timelineModelFilter.ts
> +export default class TimelineModelFilter {
let's rename this file to `index.ts` to follow the naming structure

2019-08-12 10:03 UTC, christian-bromann commented on src/timelineModel/timelineModelFilter/timelineModelViewDelegate.ts
> +export default class TimelineModelViewDelegate {
is this file needed?

2019-08-13 10:01 UTC, christian-bromann approved these changes

2019-08-13 10:11 UTC, adambabik commented on README.md
> + *   rendering: 847.373997092247,
It's in milliseconds?

2019-08-13 10:11 UTC, adambabik commented on src/common/settings.ts
> +                get: (): null => null
What exactly is it?

2019-08-13 10:11 UTC, adambabik commented on src/index.ts
> +        this._timelineLoader.init()
I assume we made sure that `init` can be called multiple times on `TimelineLoader` and it's fine?

2019-08-13 10:11 UTC, adambabik commented on src/index.ts
> +        this._timelineDetailsView = new TimelineDetailsView(performanceModel.findMainTrack())
Do we need to assign this to `this`? Is it reused later?

2019-08-13 10:11 UTC, adambabik commented on src/timelineModel/performanceModel.ts
> +            .find((track): any => track.type === TrackType.MainThread && track.forMainFrame && track.events.length)
```suggestion
            .find((track): Track => track.type === TrackType.MainThread && track.forMainFrame && track.events.length)
```

2019-08-13 10:11 UTC, adambabik commented on src/timelineModel/performanceModel.ts
> +            throw 'call setTracingModel before accessing PerformanceModel'
```suggestion
            throw new Error('call setTracingModel before accessing PerformanceModel')
```

2019-08-13 10:11 UTC, adambabik commented on src/timelineModel/performanceModel.ts
> +    public setWindow (option: {left: number, right: number}) : void {
```suggestion
    public setWindow(option: {left: number, right: number}): void {
```

2019-08-13 10:23 UTC, christian-bromann commented on README.md
> + *   rendering: 847.373997092247,
yes

2019-08-13 10:24 UTC, christian-bromann commented on src/common/settings.ts
> +                get: (): null => null
this lib doesn't need this, I assume devtools is using it to handle some sort of application settings

2019-08-13 10:24 UTC, christian-bromann commented on src/index.ts
> +        this._timelineLoader.init()
I can move it up into the constructor

2019-08-13 10:34 UTC, merged