Fetch event warning counts
saucelabs/tracelib pull request #8
Opened 2019-08-08 12:53 UTC by farhan-sauce

Fetch event warning counts

![Screen Shot 2019-08-08 at 6 17 27 PM](https://user-images.githubusercontent.com/39295560/62704407-ed954c00-ba08-11e9-99c0-7485a5cf63d4.png)

example code
```
import Tracelib from '../src/index'
import JANK_TRACE_LOG from './__fixtures__/jankTraceLog.json'

const tasks = new Tracelib(JANK_TRACE_LOG)
const counts = tasks.getWarningCounts()
console.log(counts)

# OUTPUT
{
  LongRecurringHandler: 13,
  ForcedStyle: 4684,
  ForcedLayout: 4683
}
```

### Comment
This PR should be rebased to `master` and merge only after https://github.com/saucelabs/tracelib/pull/7 gets merged.

2019-08-08 15:41 UTC, adambabik commented on src/timelineModel/timelineData.ts
>      public static forEvent(event: any): TimelineData {
Shouldn't it be `fromEvent`?

2019-08-08 15:41 UTC, adambabik approved these changes

2019-08-08 15:41 UTC, adambabik commented
Great progress, cool result!

2019-08-09 12:22 UTC, farhan-sauce commented on src/timelineModel/timelineData.ts
>      public static forEvent(event: any): TimelineData {
At present we didn't change any `className` or `method name` while porting. It's being used in different places. unchanged names will be helpful while we debug any issue and compare codebase with `devtools`.

2019-08-09 12:43 UTC, adambabik approved these changes

2019-08-09 12:43 UTC, adambabik commented on src/index.ts
> +        return performanceModel.findMainTrack().events.length
Is it possible that the main track is not found?

2019-08-09 13:11 UTC, farhan-sauce commented on src/index.ts
> +        return performanceModel.findMainTrack().events.length
Yes, good catch, I will add condition before accessing `.events`.

2019-08-09 13:43 UTC, adambabik submitted a review, later dismissed

2019-08-12 10:05 UTC, christian-bromann requested changes
one comment.

2019-08-12 10:05 UTC, christian-bromann commented on src/timelineModel/performanceModel.ts
> +    public getWarningCounts(): StatsObject {
Can we move this out of the official devtools frontend files? I would rather keep the original files as prestine as possible so that we can easier update them.

2019-08-12 10:15 UTC, adambabik commented on src/timelineModel/performanceModel.ts
> +    public getWarningCounts(): StatsObject {
So, do we copy any source code from https://github.com/ChromeDevTools/devtools-frontend?

2019-08-12 10:22 UTC, christian-bromann commented on src/timelineModel/performanceModel.ts
> +    public getWarningCounts(): StatsObject {
Not any code, just the one we need to get the data that we want.

2019-08-12 10:32 UTC, adambabik commented on src/timelineModel/performanceModel.ts
> +    public getWarningCounts(): StatsObject {
So, we actually do :d Like methods, classes etc? Maybe we should figure out some pattern like `git_sha + source_file_name + line_number` in a comment to easily keep track of that?

2019-08-12 10:37 UTC, christian-bromann commented on src/timelineModel/performanceModel.ts
> +    public getWarningCounts(): StatsObject {
to keep track on what? I would just avoid adding custom logic to the ported code from the devtools-frontend code base and put all custom logic in files that are located in a specific folder so that we now they are from us.

2019-08-12 11:10 UTC, adambabik commented on src/timelineModel/performanceModel.ts
> +    public getWarningCounts(): StatsObject {
Keep the track of what and from where exactly (by exactly I mean the git sha including) is ported. Looking at this from my perspective, I have no idea whether the `performanceModel.ts` file as a whole is ported or just some fragments. 

Of course 👍 for keeping it totally separate. We could have `src/` and `lib/` folders to distinguish what is ours and what is ported.

2019-08-13 11:00 UTC, farhan-sauce commented on src/timelineModel/performanceModel.ts
> +    public getWarningCounts(): StatsObject {
Good idea, to prevent conflicts in PRs, I would keep `src` and create new folder `custom` for now. Later after merge I will rename `src` to `devtools` and `custom` to `src`.

2019-08-13 11:33 UTC, christian-bromann requested changes

2019-08-13 11:33 UTC, christian-bromann commented on custom/warning.ts
> +    public getCounts(): StatsObject {
no need for this class .. let's move everything from this function into `getWarning` of the index file

2019-08-13 11:34 UTC, christian-bromann requested changes

2019-08-13 11:34 UTC, christian-bromann commented on custom/performanceModelUtils.ts
> +export default class PerformanceModelUtils {
I don't think we need this, just have it all in the index file directly.

2019-08-13 11:51 UTC, christian-bromann reviewed
some more suggestions

2019-08-13 11:51 UTC, christian-bromann commented on src/index.ts
> +    public findMainTrack(): Track {
```suggestion
    private _findMainTrack(): Track {
```

2019-08-13 11:51 UTC, christian-bromann commented on src/index.ts
> +            .map(( { duration } ): number => calcFPS(duration))
```suggestion
            .map(({ duration }): number => calcFPS(duration))
```

2019-08-13 11:51 UTC, christian-bromann commented on src/timelineModel/timelineData.ts
> -            event[TimelineData._symbol] = data
we should have this symbol similar to how we have it for the `InvalidationTracker` class:

```ts
    public static readonly invalidationTrackingEventsSymbol: unique symbol = Symbol('invalidationTrackingEvents')
```

2019-08-13 11:51 UTC, christian-bromann commented on tests/index.test.ts
> +    expect(result).toEqual(expected)
```suggestion
    expect(result).toMatchSnapshot()
```

2019-08-13 11:51 UTC, christian-bromann commented on tests/index.test.ts
> +    expect(result).toEqual(expected)
```suggestion
    expect(result).toEqual(56244)
```

2019-08-13 12:07 UTC, christian-bromann commented on src/index.ts
> +        if (!this._findMainTrack()) {
```suggestion
        const mainTrack = this._findMainTrack()
        if (!mainTrack) {
```

2019-08-13 12:07 UTC, christian-bromann commented on src/index.ts
> +        if (!this._findMainTrack()) {
```suggestion
        const mainTrack = this._findMainTrack()
        if (!mainTrack) {
```

2019-08-13 12:11 UTC, christian-bromann commented on src/index.ts
> +        return this._findMainTrack().events.reduce((counter: StatsObject, event: Event): StatsObject => {
```suggestion
        return mainTrack.events.reduce((counter: StatsObject, event: Event): StatsObject => {
```

2019-08-13 12:11 UTC, christian-bromann commented on src/index.ts
> +        return this._findMainTrack().events.length
```suggestion
        return mainTrack.events.length
```

2019-08-13 12:14 UTC, christian-bromann submitted a review, later dismissed
👍

2019-08-13 12:16 UTC, christian-bromann commented on src/index.ts
> +    public getMainThreadEventsLength(): number {
I don't think we need this

2019-08-13 12:22 UTC, christian-bromann approved these changes
👍

2019-08-13 12:23 UTC, merged