Fetch memory info
saucelabs/tracelib pull request #9
Opened 2019-08-09 12:27 UTC by farhan-sauce

Fetch memory info

![Screen Shot 2019-08-09 at 4 51 10 PM](https://user-images.githubusercontent.com/39295560/62778653-8e9a0a80-bace-11e9-92d5-e9926c190845.png)

example code
```
import Tracelib from '../src/index'
import JANK_TRACE_LOG from './__fixtures__/jankTraceLog.json'

const tasks = new Tracelib(JANK_TRACE_LOG)
const memoryInfo = tasks.getMemoryCounters()
console.log(memoryInfo)

# OUTPUT
{
  "jsHeapSizeUsed": { times: [
    289959946.271,
    289959983.488,
    289960044.53,        
  ], values: [
     22549008,
     20896736,
     21471160,
] },
  "documents": { times: [], values: [] },
  "nodes": { times: [], values: [] },
  "jsEventListeners": { times: [], values: [] },
  "gpuMemoryUsedKB": { times: [], values: [] },
}
```

### Comment
This PR should be rebased to `master` and merge only after https://github.com/saucelabs/tracelib/pull/8 gets merged.

2019-08-09 13:56 UTC, adambabik reviewed
Do you plan to add more unit tests?

2019-08-09 13:56 UTC, adambabik commented on src/timelineModel/counter/calculator.ts
> +    public constructor() {}
Is it needed?

2019-08-09 13:56 UTC, adambabik commented on src/timelineModel/counter/calculator.ts
> +    public computePosition(time: number): number {
Is `time` a good name here?

2019-08-09 13:56 UTC, adambabik commented on src/timelineModel/counter/counter.ts
> +        if (this.values.length && this.values[this.values.length - 1] === value) return
```suggestion
        if (this.values.slice(-1) === value) return
```

2019-08-09 13:56 UTC, adambabik commented on src/timelineModel/counter/countersGraph.ts
> +        this._calculator.setZeroTime(model ? model.timelineModel().minimumRecordTime() : 0)
From the caller perspective, `setZeroTime` can take a non-zero argument which is odd. I would try to rename `setZeroTime` to something different.

2019-08-09 13:56 UTC, adambabik commented on src/timelineModel/counter/countersGraph.ts
> +            const counters: any = event.args.data
Can we be more specific about `event.args.data` type?

2019-08-12 10:07 UTC, christian-bromann requested changes
Same here, let's make sure we don't build too much custom logic into the original devtools files so the process of updating it is easier.

2019-08-12 10:08 UTC, christian-bromann commented on src/timelineModel/counter/counter.ts
> +export default class Counter {
I assume this is our own class that you have implemented. Let's move these files into a dedicated `lib` or `custom` folder so we know which files are written by use and which are from the original code base

2019-08-13 10:42 UTC, christian-bromann commented on src/timelineModel/counter/calculator.ts
> +    public computePosition(time: number): number {
let's keep the naming of the original code base so we can identify the original code better

2019-08-13 10:48 UTC, christian-bromann commented on src/timelineModel/counter/countersGraph.ts
> +        this._calculator.setZeroTime(model ? model.timelineModel().minimumRecordTime() : 0)
same, let's keep the naming as is

2019-08-13 11:02 UTC, farhan-sauce commented on src/timelineModel/counter/counter.ts
> +export default class Counter {
`Counter` is not our own class, it's taken from [here](https://github.com/ChromeDevTools/devtools-frontend/blob/f4afd274202fc84c030cb6aeb722a811dc4ed6a2/front_end/timeline/CountersGraph.js#L255)

2019-08-13 13:08 UTC, christian-bromann approved these changes
👍

2019-08-13 13:09 UTC, merged